---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache 2 package 
    apt:
      name: apache2
      state: latest

  - name: add php supp for apache
    apt:
      name: libapache2-mod-php
      state: latest
